### PR TITLE
created LedgerAPI database

### LINKED ISSUE #1: Create Database
## Entry Table

- [ ] Entry id (primary key, non-null, auto-increment)
- [ ] Date (default to current date)
- [ ] Time (default value to current time)
- [ ] Description (non-null)
- [ ] Vendor (non-null)
- [ ] Amount (non-null)

### PR DESCRIPTION
**Pull request by alivxo**
created database

### CODE REVIEW

**Comment by alivxo** [comment]
altered database

**Comment by sekwanaa** [comment]
Haha hey Alicia, I think you just made the database in your local space, but there's no code here to help us reproduce the database in our own local server.

Please reference this to allow others to create a database from this .sql file. You may reference the section where it mentions Reverse Engineering a database.

[superuser.com/questions/396302/mysql-workbench-exporting-table-data-backup](https://superuser.com/questions/396302/mysql-workbench-exporting-table-data-backup)

**Comment by alivxo** [comment]
hey chris, i updated database let me know if you can see the update.

**Comment by alivxo** [comment]
changed ID names

**Comment by alivxo** [comment]
updated columns

**Review by sekwanaa — APPROVED** [review]
Looks good now

**Pull request merged**
